name: RandomItem2
version: '1.0-SNAPSHOT'
main: org.maseunknown.plugins.randomitem2.RandomItem2
api-version: '1.20'
commands:
  randomizer:
    description: start for all commands
    usage: /<command>
